// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD64xmTYfc143J1ragAlJ9GJFjs_4ctBbI',
    appId: '1:924618545803:web:8d12a52197345d0f46928e',
    messagingSenderId: '924618545803',
    projectId: 'workout-app-10113',
    authDomain: 'workout-app-10113.firebaseapp.com',
    storageBucket: 'workout-app-10113.firebasestorage.app',
    measurementId: 'G-XCPSK8YC81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC0wyxxAcfyVXMtB0pQDCVyO-hmC8GOE0',
    appId: '1:924618545803:android:898520b4a360c8e346928e',
    messagingSenderId: '924618545803',
    projectId: 'workout-app-10113',
    storageBucket: 'workout-app-10113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIoPsCu4q2yz6IzVSn3iBjsZjFJUEgtnY',
    appId: '1:924618545803:ios:1046010cad9ab28046928e',
    messagingSenderId: '924618545803',
    projectId: 'workout-app-10113',
    storageBucket: 'workout-app-10113.firebasestorage.app',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIoPsCu4q2yz6IzVSn3iBjsZjFJUEgtnY',
    appId: '1:924618545803:ios:1046010cad9ab28046928e',
    messagingSenderId: '924618545803',
    projectId: 'workout-app-10113',
    storageBucket: 'workout-app-10113.firebasestorage.app',
    iosBundleId: 'com.example.workoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD64xmTYfc143J1ragAlJ9GJFjs_4ctBbI',
    appId: '1:924618545803:web:eaeafe53538fc9f046928e',
    messagingSenderId: '924618545803',
    projectId: 'workout-app-10113',
    authDomain: 'workout-app-10113.firebaseapp.com',
    storageBucket: 'workout-app-10113.firebasestorage.app',
    measurementId: 'G-SDBKY4BBFZ',
  );
}
